### ISSUE TITLE
PNG images compatibility

### ISSUE THREAD

**Issue by jakemake** [samjonesigd/vue-image-zoomer#1]
Hi! Thanx for this plugin. Using it on my Vue JS project.
ISSUE: I have issue with PNG images. When i click to zoom png image, original image stays on background, so user can see 2 layers of image when mouse moving (regular and zoomed)

![image](https://user-images.githubusercontent.com/22964241/90163834-72ebd300-ddb8-11ea-8984-442be91a2d32.png)

Wanted: Regular image dissapears OR zoomed image filled by background color

**Comment by samjonesigd** [comment]
Hi @jakemake will have a look into that for you :)

**Comment by samjonesigd** [comment]
@jakemake this is fixed, if you update to the latest version. No need to set a background image.
