### ISSUE TITLE
property 'getBoundingClientRect' of undefined"

### ISSUE THREAD

**Issue by valdinei** [samjonesigd/vue-image-zoomer#10]
The component doesn't seem to find the reference to to use the "getBoundingClientRect" function

``` javascript
[Vue warn]: Error in v-on handler: "TypeError: Cannot read property 'getBoundingClientRect' of undefined"

found in

---> <ImageZoom>
       <ImageViewer> at src/components/panel/conversation/messages/messages/ImageViewer.vue
```

![image](https://user-images.githubusercontent.com/1458766/126787033-859302ff-fc26-4814-9541-408eb2e6a155.png)

**Comment by samjonesigd** [comment]
@valdinei hey, are you on the latest version? 1.2.1?

Can you show my your component so I can try replicate?
