### ISSUE TITLE
Origin parameter on mobile at init

### ISSUE THREAD

**Issue by wearemetabolism** [samjonesigd/vue-image-zoomer#11]
Hello, I'm facing a user case that require I think a new parameter.
On mobile when I touch an image, the zoomed image show up as expected with the originX and originY at zero, 
if the zoomed image has a lot of white on the edge it only display a big white square and the web user may think it is a bug.
It would be very nice to have a parameter to define the origin on mobile ( top-left, top-center, center ... )
What do you think ?
I would love to submit a PR but there is no /src
Thank you

**Comment by samjonesigd** [comment]
@wearemetabolism Added `touch-zoom-pos` on latest release.

Will add src one day, it's just used for some paid work at the moment, I know the .js file could easily be reversed :)

**Comment by wearemetabolism** [comment]
Thank you !
