### ISSUE TITLE
Add "loaded" event

### ISSUE THREAD

**Issue by fernao** [samjonesigd/vue-image-zoomer#13]
It would be wonderful if this component had an "loaded" event, in order to communicate with other components and trigger actions.

**Comment by samjonesigd** [comment]
@fernao Just when the component is loaded or the image in the component has loaded? 

Will work on it

**Comment by samjonesigd** [comment]
It used to have a placeholder image but this required javascript lazyloading when it now uses native loading attribute.

I will add lots of events for the parent to be able to look at :) including what you're wanting

**Comment by samjonesigd** [comment]
@fernao added some events and ability to add a slot as a placeholder before load, also done this one the Vue 2 legacy.

On NPM:
[v2.2.0](https://www.npmjs.com/package/vue-image-zoomer) for Vue 3
[v1.5.0](https://www.npmjs.com/package/vue-image-zoomer/v/legacy) for Legacy Vue 2
