### ISSUE TITLE
Component VueImageZoomer.vue is failing to load if used in Nuxt 3

### ISSUE THREAD

**Issue by minstn** [samjonesigd/vue-image-zoomer#14]
See https://stackblitz.com/edit/nuxt-starter-bagzmx?file=components/VueImageZoomer.client.vue

**Nuxt 3 3.0.0-rc.11**

Looks like calls to `this.$refs['vue-hover-zs']` in `mounted` hook are `null`

I know this is more of a **feature request**, but would be amazing to have this fixed!

**Comment by samjonesigd** [comment]
Feel like nextTick is better than using updated so its not firing a lot. #15

**Comment by minstn** [comment]
well done! all works nicely!
