### ISSUE TITLE
Tailwindcss breaks zoom feature of VueImageZoomer (tested with Nuxt 3)

### ISSUE THREAD

**Issue by minstn** [samjonesigd/vue-image-zoomer#16]
See here https://stackblitz.com/edit/nuxt-starter-bagzmx?file=app.vue

**Nuxt 3 v3.0.0-rc.11**
**@nuxtjs/tailwindcss v5.3.5**

Zoom feature is broken, zoomed image size is incorrectly rendered..

**Comment by samjonesigd** [comment]
Quick fix now would be to add your own css `.vh--image{max-width: none!important;}` 

I cant really add css for any possible framework :)

**Comment by minstn** [comment]
Your quick fix works 👍🏼
