### ISSUE TITLE
nextTick is not defined

### ISSUE THREAD

**Issue by monkemedia** [samjonesigd/vue-image-zoomer#18]
Good evening,

In Nuxt 3 (rc13), I get the following error `ReferenceError: nextTick is not defined`. However, the plugin still works.

<img width="499" alt="image" src="https://user-images.githubusercontent.com/14890432/201537422-5014a1a8-980c-4134-9138-7422cedba190.png">

**Comment by MiladRST** [comment]
That's true. I've faced the same error on Vue 3 ( 3.2.41 ).

**Comment by samjonesigd** [comment]
I'll fix this tonight

**Comment by samjonesigd** [comment]
Fixed here, I must have took this out by mistake #19 

@monkemedia @MiladRST
