### ISSUE TITLE
[Bug] After dynamically changing the values of regular and zoom, the enlarged image is not changed

### ISSUE THREAD

**Issue by angelofan** [samjonesigd/vue-image-zoomer#2]
### Related code
```html
<div class="zoom-box">
    <image-zoom :click-zoom="true" img-class="zoom-img" :zoom-amount="3"
                :regular="thisImgSrc"
                :zoom="thisImgSrc"
    ></image-zoom>
</div>
```

### A sample application
https://codesandbox.io/s/inspiring-christian-0p15s?file=/src/components/HelloWorld.vue

### Steps to reproduce
1. Click the change url button
![image](https://user-images.githubusercontent.com/20255750/95053996-c4af3a80-0723-11eb-9595-98459c00fed9.png)
2. The image shown has changed
![image](https://user-images.githubusercontent.com/20255750/95054017-cbd64880-0723-11eb-8016-2591eb7a308b.png)
3. Move the mouse into the image, the enlarged image has not changed
![image](https://user-images.githubusercontent.com/20255750/95054185-12c43e00-0724-11eb-8a23-869e2a588826.png)

**Comment by angelofan** [comment]
The temporary solution is to use `v-for` to render the `image-zoom` of all URLs, and then use `v-if` to render only the `image-zoom` to which the current URL belongs.

This problem still occurs when using `v-show`.

**Comment by samjonesigd** [comment]
Thanks @angelofan, should have thought about that while making it, published an update to NPM

**Comment by samjonesigd** [comment]
@angelofan was a bug from doing this that i have now fixed, if you do npm update dynamic changes will work for these props:

- breakpoints
- regular
- regular-webp
- zoom
- zoom-amount
- zoom-webp

**Comment by angelofan** [comment]
@samjonesigd Thank you for making the fix immediately, it works normally. 🎉
