### ISSUE TITLE
Tap to zoom out on mobile?

### ISSUE THREAD

**Issue by perreta** [samjonesigd/vue-image-zoomer#22]
I am currently using the legacy Vue 2 version for a Nuxt 2 project. The plugin is working great, and the desired functionality is working on desktop perfectly using :click-zoom=true. 

Just to be verbose this is: 
- Click the image to engage the zoom
- Hover around the image container to pan the zoom area
- Click the image again to disengage the zoom

On mobile the behavior is very similar, but instead of hovering, users are of course dragging, and instead of clicking the image again to disengage, users click the close button. Is it possible to configure the plugin to allow for tapping the image again on mobile to disengage zoom, or is the use of a close button required?

**Comment by samjonesigd** [comment]
@perreta I'll have a look into it :)

**Comment by samjonesigd** [comment]
Added tap-to-close prop to 1.6.0 legacy(vue2) and 2.3.0 vue3 version @perreta
