### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by Eboubaker** [samjonesigd/vue-image-zoomer#23]
```
npm i --save vue-image-zoomer
```
```vue
          <v-carousel>
            <v-carousel-item v-for="(image, index) in images" :key="index" class="carousal-image">
              <vue-image-zoomer regular="path-to-regular.jpg" />
            </v-carousel-item>
          </v-carousel>
```
```ts
import Component from "vue-class-component";
import Vue from "vue";
import VueImageZoomer from 'vue-image-zoomer'
import 'vue-image-zoomer/dist/style.css';

@Component({components: {VueImageZoomer}})
export default class Product extends Vue {
....
}
```

![image](https://github.com/samjonesigd/vue-image-zoomer/assets/37766821/ab496a13-9d1b-424a-a105-03df03f270d6)
![image](https://github.com/samjonesigd/vue-image-zoomer/assets/37766821/5b04f3c9-4025-4b56-a92c-401b0f969f92)

```json
"dependencies": {
    "@mdi/font": "^6.5.95",
    "@types/aos": "^3.0.7",
    "@vue/compiler-dom": "^3.2.40",
    "aos": "^2.3.4",
    "axios": "^0.21.4",
    "libphonenumber-js": "^1.9.17",
    "lodash": "^4.17.21",
    "moment": "^2.29.1",
    "postcss": "^8.4.20",
    "swiper": "^11.0.4",
    "text-mask-addons": "^3.8.0",
    "vue": "^2.6.11",
    "vue-awesome": "^4.1.0",
    "vue-class-component": "^7.2.3",
    "vue-image-zoomer": "^2.2.3",
    "vue-meta": "^2.4.0",
    "vue-property-decorator": "^9.1.2",
    "vue-router": "^3.2.0",
    "vue-text-mask": "^6.1.2",
    "vuetify": "^2.4.0",
    "vuex": "^3.4.0",
    "vuex-class-modules": "^1.3.0"
  },
```

**Comment by samjonesigd** [comment]
You're using Vue3 version with Vue2

**Comment by Eboubaker** [comment]
Ah I see, I did a workaround by shamelessly [stealing](https://gist.github.com/Eboubaker/f1780ef73967959900e94d2cfe1e4a89) the code of VueImageZoomer.vue and put it in my src with small tweaks

**Comment by samjonesigd** [comment]
@Eboubaker  its open source :) but the 1.5.0 version should work for you, I still maintain the Vue 2 version when I do updates. Got some coming soon

**Comment by Eboubaker** [comment]
Ok, that's nice of you, one suggestion though is to put a note in your readme after the `npm install` command to add the alternative vue2 version. because I followed the npm page readme and there is no mention of version difference there.

**Comment by samjonesigd** [comment]
@Eboubaker 

It's in the first paragraph, but I should make it make more sense :) but that's a good idea too.

![image](https://github.com/samjonesigd/vue-image-zoomer/assets/16079736/3e32d545-0e88-4e34-a213-1365c53711a1)

**Comment by Eboubaker** [comment]
Yes I Didn't see it till I started editing README.md .., you know us web developers don't like to read and go straight looking for npm install xxx commands
