### ISSUE TITLE
typescript

### ISSUE THREAD

**Issue by luckydonald** [samjonesigd/vue-image-zoomer#25]
Hey, nice plugin. 

Unfortunately typescript is screaming at me for this one not having type definitions.

**Comment by samjonesigd** [comment]
Will do a new release soon with a declaration file

**Comment by samjonesigd** [comment]
#28 Better late than never, hope this solves your issue.

**Comment by luckydonald** [comment]
Awsome, thanks 👍

**Comment by samjonesigd** [comment]
> it's not included in the npm package though, it seems. https://github.com/samjonesigd/vue-image-zoomer/blob/main/.npmignore

Embarrassing, thanks for spotting!
