### ISSUE TITLE
hover message option doesn't need how can i remove it .

### ISSUE THREAD

**Issue by Ariful491** [samjonesigd/vue-image-zoomer#31]
![image](https://github.com/user-attachments/assets/27667279-faad-4f8a-82c5-b1e610ac4e62)

**Comment by samjonesigd** [comment]
@Ariful491 2 props below will hide on desktop and touch devices

```
show-message = false
show-message-touch = false
```

**Comment by Ariful491** [comment]
it's not working.

**Comment by samjonesigd** [comment]
@Ariful491 will sort it very soon :)

**Comment by samjonesigd** [comment]
@Ariful491 just tested this, it does work, make sure you put the colon on the prop like below

```
:show-message="false"
:show-message-touch="false"
```
