### ISSUE TITLE
Property imgHeight and imgWidth expects Number

### ISSUE THREAD

**Issue by antonioferngarcia** [samjonesigd/vue-image-zoomer#33]
The properties imgHeight and imgWidth expects only Number types but i think should expect String or Number to allow values like "100%" or "10rem".
Now if you pass 100% as value it works and component style is updated as desired but in console appears a huge warning.

Thank you so much for this amazing library

**Comment by samjonesigd** [comment]
This is just for width and height attributes for the img element that accepts pixels only, its due to chrome asking for this in lighthouse.  Allowing it to take up space before it loads, to mitigate content layout shifts 

[](https://www.w3schools.com/tags/att_img_width.asp)
