### ISSUE TITLE
customize "reduce size button" position

### ISSUE THREAD

**Issue by mafrego** [samjonesigd/vue-image-zoomer#4]
Hi samjonesigd,

great job with your image zoomer!
I noticed that when I use the zoomer on a mobile device the button to reduce the image to the normal size is at the top left.
I'd like to ask you if it is possible to change that position somehow or even better have the possibility to customize it.
Thank you very much!

**Comment by samjonesigd** [comment]
Hi @mafrego 

Thank you! 

Added some new props, to change position of the close element and the message element.
Look for props "close-pos" & "message-pos".
You can override the CSS yourself if needed to be more custom. I have updated here and published to npm.

Always looking for new ideas to upgrade this plugin!
