### ISSUE TITLE
message-position remains at the bottom

### ISSUE THREAD

**Issue by mafrego** [samjonesigd/vue-image-zoomer#5]
Hi Sam,

thanks for the new props.
Is "message-position" prop supposed to work on desktop/laptop browsers or on mobile devices?
I'm asking because I've just tested "message-position" both on computer browsers (Firefox, Chrome) and on mobile (Samsung, iphone, Nexus, etc. Chrome, Firefox, Safari) browsers and it doesn't work: the message position remains at the bottom even if the position is set to top.
Thanks!

**Comment by samjonesigd** [comment]
@mafrego sorry, this should be "message-pos" I'll update the readme soon :)
