### ISSUE TITLE
No hover default message 

### ISSUE THREAD

**Issue by mafrego** [samjonesigd/vue-image-zoomer#6]
Hi Sam,

is it possible not to have any message with the hover option? Neither a default nor a custom message?
I'm asking because I tried to set an empty string with the "hover-message" property but the zoomer still displays the grey background.
Put another way, is it possible not to have the grey background when the "hover-message" property is set to an empty string?
Thanks

**Comment by samjonesigd** [comment]
@mafrego I can add a prop later today, but you could just do `.vh--message{display:none;}` in css

**Comment by samjonesigd** [comment]
Hi @mafrego 

2 new props:
- show-message
- show-message-touch

You can set these to false if you do not want the message to show. First one is for non-touch devices only, second for touch devices only.
