### ISSUE TITLE
regular image size property

### ISSUE THREAD

**Issue by mafrego** [samjonesigd/vue-image-zoomer#7]
Hi Sam,

would it be possible to add a property to insert the regular image size (height/width) so that browsers can calculate the actual height BEFORE the image is loaded.
This avoid that the content jumps as soon as the images is loaded.
https://css-tricks.com/preventing-content-reflow-from-lazy-loaded-images

Thanks!

**Comment by samjonesigd** [comment]
@mafrego do you think allowing a placeholder image would better? then you don't have to set a width and height.

You can use a small file sized image, one colour or transparent
