### ISSUE TITLE
Error importing the component

### ISSUE THREAD

**Issue by wealthyboy** [samjonesigd/vue-image-zoomer#8]
import imageZoom from 'vue-image-zoomer';

When i try to import the component  i get: 

Could not find a declaration file for module 'vue-image-zoomer'. '/Applications/XAMPP/xamppfiles/htdocs/AM/node_modules/vue-image-zoomer/dist/vueImageZoom.js' implicitly has an 'any' type.

**Comment by samjonesigd** [comment]
@wealthyboy this wasn’t built to work with typescript. Try the require way to import instead and let me know if that works. If not I’ll look at making it typescript compatible

**Comment by wealthyboy** [comment]
@samjonesigd I'm not using typescript. 


When i try to require it says the same

**Comment by samjonesigd** [comment]
@wealthyboy that is an error you get with typescript
